(()=>{'use strict';
let assets=[];let loaded=false;
const $=(s,r=document)=>r.querySelector(s);
const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function findAsset(name){const n=norm(name);return assets.find(a=>norm(a.source||'').includes(n)||norm((a.source||'').split('/').pop())===n)||null}
function enhance(name){const modal=$('#arsipModal');if(!modal||modal.hidden)return;const pv=$('.pv',modal);if(!pv)return;const asset=findAsset(name);if(!asset)return;const url=asset.cloudinary_url||asset.source;if(!url)return;const kind=asset.kind||'';let viewer='';if(kind==='pdf'||/\.pdf($|\?)/i.test(url))viewer=`<iframe class="real-doc-view" src="${esc(url)}#toolbar=1&view=FitH" title="Pratinjau ${esc(name)}"></iframe>`;else if(kind==='document'||/\.(docx?|pptx?|xlsx?)($|\?)/i.test(url)){const office='https://view.officeapps.live.com/op/view.aspx?src='+encodeURIComponent(url);viewer=`<iframe class="real-doc-view" src="${office}" title="Pratinjau ${esc(name)}"></iframe>`}else if(kind==='image')viewer=`<div class="real-image-wrap"><img src="${esc(url)}" alt="${esc(name)}"></div>`;else if(kind==='audio')viewer=`<audio class="real-audio" controls preload="metadata" src="${esc(url)}"></audio>`;else viewer=`<iframe class="real-doc-view" src="${esc(url)}" title="Pratinjau ${esc(name)}"></iframe>`;
pv.innerHTML=`<div class="real-preview"><div class="real-preview-head"><div><span>PRATINJAU BERKAS ASLI</span><h3>${esc(name)}</h3></div><a href="${esc(url)}" target="_blank" rel="noopener">Buka berkas ↗</a></div>${viewer}<div class="real-preview-foot">Sumber berkas tersedia melalui penyimpanan digital. Jika dokumen Word tidak tampil di dalam bingkai, gunakan tombol <b>Buka berkas</b>.</div></div>`}
function css(){if($('#arsip-real-preview-style'))return;const s=document.createElement('style');s.id='arsip-real-preview-style';s.textContent=`.real-preview{height:100%;display:flex;flex-direction:column;min-height:650px}.real-preview-head{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:4px 0 14px}.real-preview-head span{font-size:.72rem;font-weight:900;letter-spacing:.1em;color:#075aa4}.real-preview-head h3{margin:4px 0 0;color:#092b55}.real-preview-head a{display:inline-flex;padding:9px 12px;border-radius:9px;background:#075aa4;color:#fff;text-decoration:none;font-weight:900;font-size:.8rem;white-space:nowrap}.real-doc-view{width:100%;height:min(68vh,720px);border:1px solid #d9e5ec;border-radius:12px;background:#fff}.real-image-wrap{display:grid;place-items:center;min-height:400px;background:#eef4f7;border-radius:12px;padding:15px}.real-image-wrap img{max-width:100%;max-height:68vh;object-fit:contain}.real-audio{width:100%;margin:80px 0}.real-preview-foot{margin-top:10px;color:#687f90;font-size:.78rem;line-height:1.55}@media(max-width:560px){.real-preview{min-height:0}.real-preview-head{align-items:flex-start;flex-direction:column}.real-doc-view{height:70vh}.real-preview-head a{width:100%;justify-content:center}}`;document.head.appendChild(s)}
async function boot(){css();try{const r=await fetch('data/pcmcepu-media.json',{cache:'no-store'});if(r.ok){const d=await r.json();assets=Array.isArray(d.assets)?d.assets:[]}}catch(e){}document.addEventListener('click',e=>{const b=e.target.closest?.('[data-one]');if(!b)return;const name=decodeURIComponent(b.dataset.one||'');setTimeout(()=>enhance(name),80)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();