(()=>{'use strict';
let assets=[];
const $=(s,r=document)=>r.querySelector(s);
const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,'');
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function findAsset(name){const n=norm(name);return assets.find(a=>norm(a.source||'').includes(n)||norm((a.source||'').split('/').pop())===n)||null}
function isDoc(name){return /\.(doc|docx)$/i.test(name)}
function css(){if($('#arsip-real-preview-style'))return;const s=document.createElement('style');s.id='arsip-real-preview-style';s.textContent=`.real-preview{height:100%;display:flex;flex-direction:column;min-height:650px}.real-preview-head{display:flex;justify-content:space-between;gap:14px;align-items:center;padding:4px 0 14px}.real-preview-head span{font-size:.72rem;font-weight:900;letter-spacing:.1em;color:#075aa4}.real-preview-head h3{margin:4px 0 0;color:#092b55}.real-preview-head a{display:inline-flex;padding:9px 12px;border-radius:9px;background:#075aa4;color:#fff;text-decoration:none;font-weight:900;font-size:.8rem;white-space:nowrap}.real-doc-view{width:100%;height:min(72vh,760px);border:1px solid #d9e5ec;border-radius:12px;background:#fff}.real-image-wrap{display:grid;place-items:center;min-height:400px;background:#eef4f7;border-radius:12px;padding:15px}.real-image-wrap img{max-width:100%;max-height:72vh;object-fit:contain}.real-audio{width:100%;margin:80px 0}.real-html{height:min(72vh,760px);overflow:auto;border:1px solid #d9e5ec;border-radius:12px;background:#fff;padding:28px;color:#203d57;line-height:1.7}.real-empty{display:grid;place-items:center;min-height:420px;padding:30px;text-align:center;border:1px dashed #bfd3df;border-radius:16px;background:linear-gradient(135deg,#f7fcff,#f4fbfa)}.real-empty h4{margin:0 0 8px;color:#092b55;font-size:1.2rem}.real-empty p{max-width:650px;margin:0;color:#60798b;line-height:1.65}.real-preview-foot{margin-top:10px;color:#687f90;font-size:.78rem;line-height:1.55}@media(max-width:560px){.real-preview{min-height:0}.real-preview-head{align-items:flex-start;flex-direction:column}.real-doc-view{height:72vh}.real-preview-head a{width:100%;justify-content:center}.real-html{padding:18px 14px}}`;document.head.appendChild(s)}
function render(name,asset){const modal=$('#arsipModal');if(!modal||modal.hidden)return;const pv=$('.pv',modal);if(!pv)return;const url=asset?.preview_url||asset?.pdf_url||asset?.cloudinary_url||asset?.url||asset?.source||'';const kind=asset?.kind||'';let viewer='';if(asset?.preview_html){viewer=`<article class="real-html">${asset.preview_html}</article>`}else if(url&&((kind==='pdf')||/\.pdf($|\?)/i.test(url))){viewer=`<iframe class="real-doc-view" src="${esc(url)}#toolbar=1&view=FitH" title="Pratinjau lengkap ${esc(name)}"></iframe>`}else if(url&&kind==='image'){viewer=`<div class="real-image-wrap"><img src="${esc(url)}" alt="${esc(name)}"></div>`}else if(url&&kind==='audio'){viewer=`<audio class="real-audio" controls preload="metadata" src="${esc(url)}"></audio>`}else if(url&&isDoc(name)&&navigator.onLine){const office='https://view.officeapps.live.com/op/view.aspx?src='+encodeURIComponent(url);viewer=`<iframe class="real-doc-view" src="${office}" title="Pratinjau lengkap ${esc(name)}"></iframe>`}else if(url&&!isDoc(name)){viewer=`<iframe class="real-doc-view" src="${esc(url)}" title="Pratinjau lengkap ${esc(name)}"></iframe>`}else{viewer=`<div class="real-empty"><div><h4>Isi dokumen belum tersedia di paket situs</h4><p>Metadata berkas sudah tersedia, tetapi berkas fisik atau versi PDF/HTML-nya belum terhubung ke katalog. Saya sengaja tidak menampilkan kartu pajangan yang disebut “pratinjau”. Begitu <b>preview_url</b> atau berkas asli masuk ke manifest, area ini menampilkan isi dokumen secara penuh.</p></div></div>`}
pv.innerHTML=`<div class="real-preview"><div class="real-preview-head"><div><span>PRATINJAU ISI BERKAS</span><h3>${esc(name)}</h3></div>${url?`<a href="${esc(url)}" target="_blank" rel="noopener">Buka berkas ↗</a>`:''}</div>${viewer}<div class="real-preview-foot">Pratinjau berarti isi berkas asli. Metadata tidak diperlakukan sebagai isi dokumen.</div></div>`}
function enhance(name){render(name,findAsset(name))}
async function boot(){css();try{const r=await fetch('data/pcmcepu-media.json',{cache:'no-store'});if(r.ok){const d=await r.json();assets=Array.isArray(d.assets)?d.assets:[]}}catch(e){}document.addEventListener('click',e=>{const b=e.target.closest?.('[data-one]');if(!b)return;const name=decodeURIComponent(b.dataset.one||'');setTimeout(()=>enhance(name),20)},true)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();