(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s);
let current=null,scale=1,ready=false;
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
function css(){if($('#pcm-doc-preview-style'))return;const s=document.createElement('style');s.id='pcm-doc-preview-style';s.textContent=`.pcm-dv{position:fixed;inset:0;z-index:999999;background:#111;display:flex;align-items:center;justify-content:center}.pcm-dv[hidden]{display:none}.pcm-dv-shell{width:min(1220px,98vw);height:min(96vh,980px);background:#222;border-radius:14px;overflow:hidden;display:flex;flex-direction:column;box-shadow:0 30px 100px #0008}.pcm-dv-head{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 12px;background:#202020;color:#fff}.pcm-dv-head h2{margin:0;color:#fff;font-size:.96rem;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pcm-dv-head small{color:#ffd84a;font-weight:900}.pcm-dv-actions{display:flex;gap:5px;align-items:center;flex-wrap:wrap}.pcm-dv-btn{border:1px solid #777;background:#333;color:#fff;border-radius:7px;padding:7px 10px;font:inherit;font-weight:900;cursor:pointer}.pcm-dv-btn:hover{background:#444}.pcm-dv-btn.download{background:#ffd04a;color:#382500;border-color:#ffd04a}.pcm-dv-stage{flex:1;overflow:auto;background:#303030;padding:12px;display:flex;justify-content:center;align-items:flex-start}.pcm-dv-zoom{transform-origin:top center;transition:transform .12s ease;min-width:0}.pcm-dv-frame{display:block;width:calc(min(1180px,94vw));height:calc(min(88vh,880px));min-height:680px;border:0;background:#fff}.pcm-dv-image{display:block;max-width:100%;height:auto;background:#fff;box-shadow:0 12px 35px #0008}.pcm-dv-paper{width:min(920px,94vw);min-height:100%;background:#fff;padding:42px 48px;color:#294d68;line-height:1.9;box-shadow:0 12px 35px #0008;white-space:pre-wrap}.pcm-dv-empty{margin:50px auto;max-width:720px;padding:30px;background:#fff;border-radius:12px;color:#587188;text-align:center;line-height:1.7}.pcm-dv-foot{padding:7px 12px;background:#202020;color:#dce7ee;font-size:.7rem}@media(max-width:560px){.pcm-dv{padding:0}.pcm-dv-shell{width:100%;height:100%;border-radius:0}.pcm-dv-head{align-items:flex-start}.pcm-dv-head h2{font-size:.86rem}.pcm-dv-stage{padding:4px}.pcm-dv-frame{width:100%;height:calc(100vh - 105px);min-height:600px}.pcm-dv-paper{width:100%;padding:25px 16px}}`;document.head.appendChild(s)}
function shell(){let m=$('#pcmDocPreview');if(m)return m;css();m=document.createElement('div');m.id='pcmDocPreview';m.className='pcm-dv';m.hidden=true;m.innerHTML=`<div class="pcm-dv-shell"><div class="pcm-dv-head"><div style="min-width:0"><small>DOKUMEN · PRATINJAU LOKAL</small><h2 id="pcmDvTitle"></h2></div><div class="pcm-dv-actions"><button class="pcm-dv-btn" data-dv-zoom="-">−</button><button class="pcm-dv-btn" data-dv-reset>100%</button><button class="pcm-dv-btn" data-dv-zoom="+">+</button><button class="pcm-dv-btn download" data-dv-download>↓ Download</button><button class="pcm-dv-btn" data-dv-close>×</button></div></div><div id="pcmDvStage" class="pcm-dv-stage"></div><div class="pcm-dv-foot">Ruang baca tetap di situs ini · isi ditampilkan dari berkas yang terhubung ke katalog</div></div>`;document.body.appendChild(m);m.addEventListener('click',e=>{if(e.target===m||e.target.closest('[data-dv-close]'))close();if(e.target.closest('[data-dv-zoom]'))zoom(e.target.closest('[data-dv-zoom]').dataset.dvZoom);if(e.target.closest('[data-dv-reset]'))zoom('reset');if(e.target.closest('[data-dv-download]'))download()});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!m.hidden)close()});return m}
function download(){if(!current?.url)return;const a=document.createElement('a');a.href=current.url;a.download=current.name||'dokumen';a.rel='noopener';document.body.appendChild(a);a.click();a.remove()}
function zoom(dir){if(dir==='+')scale=Math.min(3,scale+.15);else if(dir==='-')scale=Math.max(.5,scale-.15);else scale=1;const z=$('#pcmDvZoom');if(z)z.style.transform=`scale(${scale})`}
async function open(opt){const m=shell();current={title:opt.title||'Dokumen',url:opt.url||'',name:opt.name||'dokumen'};scale=1;$('#pcmDvTitle').textContent=current.title;m.hidden=false;document.body.style.overflow='hidden';const stage=$('#pcmDvStage');stage.innerHTML='<div class="pcm-dv-empty">Memuat dokumen…</div>';if(!current.url){stage.innerHTML='<div class="pcm-dv-empty"><b>Dokumen belum tersedia.</b><br>Berkas fisik belum terhubung ke katalog ini.</div>';return}const u=current.url;if(/\.pdf(?:$|\?)/i.test(u)){stage.innerHTML=`<div id="pcmDvZoom" class="pcm-dv-zoom"><iframe class="pcm-dv-frame" src="${esc(u)}#toolbar=1&navpanes=0&view=FitH" title="Dokumen"></iframe></div>`;return}if(/\.(png|jpe?g|webp|gif|svg)(?:$|\?)/i.test(u)){stage.innerHTML=`<div id="pcmDvZoom" class="pcm-dv-zoom"><img class="pcm-dv-image" src="${esc(u)}" alt=""></div>`;return}if(/\.(txt|md|html?)(?:$|\?)/i.test(u)){try{const r=await fetch(u,{cache:'force-cache'});const t=await r.text();stage.innerHTML=`<div id="pcmDvZoom" class="pcm-dv-zoom"><article class="pcm-dv-paper">${esc(t)}</article></div>`}catch(_){stage.innerHTML='<div class="pcm-dv-empty"><b>Dokumen gagal dimuat.</b></div>'};return}stage.innerHTML='<div class="pcm-dv-empty"><b>Format dokumen ini belum dapat dirender langsung.</b><br>Tombol Download tetap mengambil berkas yang terhubung tanpa membuka halaman situs lain.</div>'}
function close(){const m=$('#pcmDocPreview');if(m)m.hidden=true;document.body.style.overflow='';current=null}
async function pustakaUrl(title){try{const [a,b]=await Promise.all([fetch('data/pustaka-books.json?v=25',{cache:'no-store'}),fetch('data/pustaka-catalog.json?v=25',{cache:'no-store'})]);const arr=[];for(const r of [a,b]){if(r.ok){const d=await r.json();arr.push(...(d.items||[]))}}const x=arr.find(v=>(v.title||v.name)===title);return x?.cloudinary_url||x?.preview_url||x?.file_url||x?.url||''}catch(_){return''}}
async function arsipUrl(name){try{const r=await fetch('data/arsip-somagede.json?v=25',{cache:'no-store'});if(!r.ok)return'';const d=await r.json(),x=(d.records||[]).find(v=>v.name===name);if(x?.preview_url||x?.cloudinary_url||x?.file_url)return x.preview_url||x.cloudinary_url||x.file_url;const n=String(name||'').trim(),b=n.replace(/\.(docx?|pptx?|xlsx?|pdf|html?)$/i,'');const cs=[`/arsip/${encodeURIComponent(n)}`,`/arsip/${encodeURIComponent(b)}.pdf`,`/arsip/${encodeURIComponent(b)}.docx`,`/arsip/${encodeURIComponent(b)}.doc`,`/arsip/${encodeURIComponent(b)}.html`];for(const u of cs){try{const h=await fetch(u,{method:'HEAD',cache:'no-store'});if(h.ok)return u}catch(_){}}return''}catch(_){return''}}
function installCapture(){if(ready)return;ready=true;document.addEventListener('click',async e=>{const p=e.target.closest?.('#p3grid [data-open]');if(p){e.preventDefault();e.stopImmediatePropagation();const card=p.closest('.p3card'),title=card?.querySelector('h3')?.textContent?.trim()||'';const url=await pustakaUrl(title);open({title,url,name:title.replace(/[^a-z0-9]+/gi,'-')+'.pdf'});return}const a=e.target.closest?.('#arsip [data-one]');if(a){e.preventDefault();e.stopImmediatePropagation();const name=decodeURIComponent(a.dataset.one||'');const url=await arsipUrl(name);open({title:name,url,name});return}},true)}
installCapture();window.PCMDocumentPreview={open,close};
})();
