(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const PANEL_IDS=new Set(['beranda','berita','pustaka','quran','kta','arsip','suara','kontak','struktur']);
const beritaIds=new Set(['profil','kajian','agenda']);let lastPointer=0;
function loadScript(src,id){if(document.getElementById(id))return;const s=document.createElement('script');s.src=src;s.id=id;s.defer=true;document.body.appendChild(s)}
function loadPustaka(){loadScript('pcmcepu-content-ui.js?v=20260825-10','library-content-loader');return window.PCMCepuContent}
function loadCore(){loadScript('quran-ui.js?v=20260825-10','quran-local-loader');loadScript('arsip-ui.js?v=20260825-10','arsip-local-loader');loadScript('arsip-preview.js?v=20260825-10','arsip-preview-loader');loadScript('site-v6.js?v=20260825-10','site-v6-loader')}
function active(id,sub){const target=$('#'+id)||$('#beranda');$$('.panel').forEach(p=>p.classList.toggle('active',p===target));$$('.nav-item').forEach(a=>a.removeAttribute('aria-current'));const main=$(`.nav-item[href="#${id}"]`);if(main)main.setAttribute('aria-current','page');if(sub&&id==='berita'){$(`#bmTabs [data-bm="${sub}"]`)?.click()}if(sub&&id==='arsip')window.PCMArsip?.focus?.(sub);window.scrollTo(0,0)}
function normalizeMenus(){const berita=$('.nav-drop .nav-parent[href="#berita"]')?.parentElement?.querySelector('.submenu');if(berita)berita.innerHTML='<a href="#profil">Profil Pimpinan</a><a href="#kajian">Kajian Rutin</a><a href="#agenda">Agenda Persyarikatan</a><a href="#struktur">Susunan Lengkap</a>';const pustaka=$('.nav-drop .nav-parent[href="#pustaka"]')?.parentElement?.querySelector('.submenu');if(pustaka)pustaka.innerHTML='<a href="#khutbah">KhutbahMu</a><a href="#buku">BukuMu</a><a href="#hadits">HaditsMu</a><a href="#quran">Al-Qur’anMu</a>';const arsip=$('.nav-drop .nav-parent[href="#arsip"]')?.parentElement?.querySelector('.submenu');if(arsip)arsip.innerHTML='<a href="#pedoman">Pedoman Surat</a><a href="#masuk">Surat Masuk</a><a href="#keluar">Surat Keluar</a><a href="#lampiran-keluar">Lampiran Surat Keluar</a><a href="#dokumen-lainnya">Dokumen Lainnya</a><a href="#wakaf">Data Wakaf</a>'}
function route(link){const href=link.getAttribute('href')||'';if(!href.startsWith('#'))return false;const id=href.slice(1);const drop=link.closest('.nav-drop');const parent=(drop?.querySelector('.nav-parent')?.getAttribute('href')||'').slice(1);if(beritaIds.has(id)){active('berita',id);return true}if(id==='struktur'){active('struktur');return true}if(id==='quran'){active('quran');loadCore();setTimeout(()=>window.PCMQuran?.mount?.(),0);return true}if(['khutbah','buku','hadits'].includes(id)){active('pustaka');loadPustaka();setTimeout(()=>window.PCMCepuContent?.render?.(id,id==='khutbah'?'KhutbahMu':id==='buku'?'BukuMu':'HaditsMu',id==='khutbah'?'khutbah':'pustaka'),0);return true}if(['pedoman','masuk','keluar','lampiran-keluar','dokumen-lainnya','wakaf'].includes(id)){active('arsip');loadCore();setTimeout(()=>window.PCMArsip?.mount?.(),0);setTimeout(()=>window.PCMArsip?.focus?.(id),20);return true}if(drop&&parent&&PANEL_IDS.has(parent)){active(parent);if(parent==='pustaka'){loadPustaka();setTimeout(()=>window.PCMCepuContent?.render?.('pustaka','PustakaMu','pustaka'),0)}if(parent==='arsip')setTimeout(()=>window.PCMArsip?.mount?.(),0);return true}if(PANEL_IDS.has(id)){active(id);if(id==='pustaka'){loadPustaka();setTimeout(()=>window.PCMCepuContent?.render?.('pustaka','PustakaMu','pustaka'),0)}if(id==='quran')loadCore();if(id==='arsip')setTimeout(()=>window.PCMArsip?.mount?.(),0);return true}return false}
function polish(){if($('#pcm-fast-ui'))return;const s=document.createElement('style');s.id='pcm-fast-ui';s.textContent=`html{scroll-behavior:auto!important}body{overscroll-behavior-x:none;background:radial-gradient(circle at 8% 0,#e8f8ff 0,#f5f9fd 34%,#f4f7fb 100%)}.panel.active{display:block!important;animation:none!important;transition:none!important}.panel{content-visibility:auto}.main-nav{position:relative;z-index:100;box-shadow:0 8px 24px rgba(4,48,88,.16);overflow:visible!important}.nav-inner{contain:layout}.nav-drop{position:relative;z-index:120;overflow:visible!important}.submenu{z-index:1000!important;position:absolute!important;top:calc(100% + 8px)!important;left:0!important;min-width:220px!important;max-height:min(70vh,520px);overflow:auto!important;box-shadow:0 18px 45px rgba(4,40,72,.22)!important}.nav-item,.submenu a,button{touch-action:manipulation;-webkit-tap-highlight-color:transparent}.nav-item{transition:transform .06s linear!important}@media(max-width:700px){.main-nav{z-index:500}.nav-drop.v6-open .submenu{display:block!important;position:fixed!important;top:var(--v6-menu-top,90px)!important;left:10px!important;right:10px!important;width:auto!important;max-height:70vh!important;border-radius:18px!important;z-index:5000!important}.nav-drop.v6-open{z-index:5001}.nav-inner{overflow-x:auto;scrollbar-width:none}.nav-inner::-webkit-scrollbar{display:none}}@media(max-width:560px){.nav-inner{justify-content:flex-start!important;flex-wrap:nowrap!important;padding:8px!important;gap:6px!important}.nav-item{white-space:nowrap;font-size:.86rem!important;padding:9px 10px!important}.nav-drop{flex:0 0 auto}.grid{grid-template-columns:1fr!important}.history{padding:20px 15px!important}.history p{font-size:.94rem;line-height:1.75}}@media(prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}`;document.head.appendChild(s)}
function registerOffline(){if(!('serviceWorker'in navigator))return;navigator.serviceWorker.register('sw.js?v=20260825-10',{scope:'./'}).then(r=>r.update()).catch(()=>{})}
function install(){polish();normalizeMenus();loadCore();registerOffline();setTimeout(()=>loadPustaka(),0);window.addEventListener('pointerdown',e=>{const a=e.target.closest?.('a[href^="#"]');if(!a)return;if(a.classList.contains('nav-parent')&&innerWidth<=700){e.preventDefault();e.stopImmediatePropagation();const d=a.closest('.nav-drop');const was=d?.classList.contains('v6-open');$$('.nav-drop').forEach(x=>x.classList.remove('v6-open'));if(d&&!was){d.classList.add('v6-open');document.documentElement.style.setProperty('--v6-menu-top',(document.querySelector('.main-nav')?.getBoundingClientRect().bottom||120)+'px')}lastPointer=performance.now();return}if(route(a)){e.preventDefault();e.stopImmediatePropagation();lastPointer=performance.now()}},{capture:true,passive:false});window.addEventListener('click',e=>{const a=e.target.closest?.('a[href^="#"]');if(!a)return;if(performance.now()-lastPointer<700){e.preventDefault();e.stopImmediatePropagation();return}if(route(a)){e.preventDefault();e.stopImmediatePropagation()}},{capture:true});if(location.hash){const a=$(`a[href="${location.hash}"]`);if(a)route(a)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();