(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let mounted=false,active='bukhari',chapter=1,loading=false,cache=new Map();
const TAG='v1.2.0',RAW='https://raw.githubusercontent.com/AhmedBaset/hadith-json/'+TAG+'/db/by_chapter/the_9_books/';
const CDN='https://cdn.jsdelivr.net/gh/AhmedBaset/hadith-json@'+TAG+'/db/by_chapter/the_9_books/';
const books=[
 ['bukhari','Shahih Bukhari','صحيح البخاري','Imam Muhammad ibn Ismail al-Bukhari',97,'#0b6b55'],
 ['muslim','Shahih Muslim','صحيح مسلم','Imam Muslim ibn al-Hajjaj',56,'#174a8a'],
 ['abu-daud','Sunan Abu Daud','سنن أبي داود','Imam Abu Dawud',43,'#7a4b18'],
 ['tirmidzi','Sunan Tirmidzi','جامع الترمذي','Imam at-Tirmidhi',49,'#8b2430'],
 ['nasai','Sunan an-Nasa’i','سنن النسائي','Imam an-Nasa’i',52,'#5b3a91'],
 ['ibnu-majah','Sunan Ibnu Majah','سنن ابن ماجه','Imam Ibn Majah',37,'#2f5d50'],
 ['malik','Al-Muwatta','الموطأ','Imam Malik ibn Anas',61,'#8a5a16'],
 ['ahmad','Musnad Ahmad','مسند أحمد','Imam Ahmad ibn Hanbal',8,'#234f73'],
 ['darimi','Sunan ad-Darimi','سنن الدارمي','Imam ad-Darimi',24,'#68452f']
];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const info=id=>books.find(x=>x[0]===id)||books[0];
function styles(){if($('#hadits-v16-style'))return;const s=document.createElement('style');s.id='hadits-v16-style';s.textContent=`
#hadits .hd-wrap{max-width:1220px;margin:auto;padding:18px 0 60px;position:relative}#hadits .hd-wrap:before{content:'';position:absolute;inset:0;background:url('motif-sudut-somagede.svg') left top/180px auto no-repeat,url('motif-sudut-somagede.svg') right bottom/210px auto no-repeat;opacity:.045;pointer-events:none}.hd-wrap>*{position:relative;z-index:1}
.hd-hero{padding:34px 28px;border-radius:28px;color:#fff;background:linear-gradient(135deg,#062653,#075aa4 55%,#0b8f87);box-shadow:0 20px 55px #06265320}.hd-kicker{color:#ffd84a;font-weight:1000;font-size:.72rem;letter-spacing:.15em}.hd-hero h1{margin:5px 0;color:#fff;font-size:clamp(2rem,5vw,3.6rem)}.hd-hero p{max-width:820px;color:#e9f8ff}.hd-tools{display:flex;gap:9px;flex-wrap:wrap;margin:17px 0}.hd-search{flex:1 1 280px;padding:13px 15px;border:1px solid #cbdde8;border-radius:14px;font:inherit}
.hd-bookgrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.hd-book{border:1px solid #d8e6ee;background:#fff;border-radius:18px;padding:13px;box-shadow:0 9px 26px #06265310;min-width:0}.hd-book.active{border-color:#0b8f87;box-shadow:0 12px 30px #0b8f8728}.hd-cover{height:235px;border-radius:12px;padding:14px;display:flex;flex-direction:column;justify-content:space-between;color:#fff;position:relative;overflow:hidden;box-shadow:inset 0 0 0 2px #ffffff22,0 8px 18px #0002}.hd-cover:before{content:'';position:absolute;inset:8px;border:1px solid #ffffff55;border-radius:8px}.hd-cover:after{content:'☾';position:absolute;right:15px;top:12px;font-size:1.5rem;color:#ffd84a}.hd-cover>*{position:relative;z-index:1}.hd-cover .arab{font-family:serif;font-size:1.65rem;text-align:center;margin-top:28px}.hd-cover .latin{text-align:center;font-size:1rem;font-weight:1000;line-height:1.35}.hd-cover .author{text-align:center;font-size:.72rem;opacity:.92}.hd-meta{padding:12px 3px 2px}.hd-meta strong{display:block;color:#082d58;font-size:1rem}.hd-meta small{display:block;color:#6c8293;margin-top:4px}.hd-book-actions{display:flex;gap:7px;margin-top:10px}.hd-btn{border:1px solid #cbdde8;background:#fff;color:#174563;border-radius:10px;padding:9px 11px;font:inherit;font-weight:900;cursor:pointer}.hd-btn.primary{background:#075aa4;color:#fff;border-color:#075aa4}.hd-btn:disabled{opacity:.55;cursor:wait}
.hd-reader{margin-top:18px;border:1px solid #d8e6ee;border-radius:22px;background:rgba(255,255,255,.94);overflow:hidden;box-shadow:0 15px 38px #06265310}.hd-reader-head{padding:20px 22px;background:linear-gradient(135deg,#f0fbff,#fff9ea);border-bottom:1px solid #dfeaf0}.hd-reader-head h2{margin:0;color:#082d58}.hd-reader-head p{margin:5px 0;color:#60788b}.hd-chapters{display:flex;gap:7px;overflow:auto;padding:12px 22px;border-bottom:1px solid #e2ebf0;background:#fbfdfe}.hd-chapters button{white-space:nowrap}.hd-list{padding:8px 22px 28px}.hd-item{padding:20px 0;border-bottom:1px solid #e2ebf0}.hd-item:last-child{border-bottom:0}.hd-num{font-size:.74rem;color:#0b8f87;font-weight:1000}.hd-arab{direction:rtl;text-align:right;font-family:serif;font-size:1.4rem;line-height:2.1;color:#172f46;margin:10px 0}.hd-en{margin:7px 0;color:#294d68;line-height:1.85}.hd-note{color:#60788b;font-size:.8rem}.hd-empty{padding:30px;text-align:center;color:#60788b}.hd-pager{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:14px 22px;border-top:1px solid #e2ebf0;background:#fbfdfe}.hd-pager span{color:#60788b;font-size:.85rem;text-align:center}.hd-progress{padding:10px 14px;background:#fff8df;color:#765719;border-bottom:1px solid #eadca8;font-size:.82rem}
@media(max-width:850px){.hd-bookgrid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.hd-hero{padding:26px 18px}.hd-bookgrid{grid-template-columns:1fr}.hd-cover{height:255px}.hd-list{padding-left:16px;padding-right:16px}.hd-pager{padding-left:16px;padding-right:16px}.hd-item{padding:17px 0}.hd-arab{font-size:1.2rem}}
`;document.head.appendChild(s)}
async function fetchChapter(id,n){const key=id+':'+n;if(cache.has(key))return cache.get(key);let last;for(const base of [CDN,RAW]){try{const r=await fetch(base+encodeURIComponent(id)+'/'+n+'.json',{cache:'force-cache'});if(!r.ok)throw new Error('HTTP '+r.status);const d=await r.json();const a=(d?.hadiths||[]).map(x=>({number:x.idInBook??x.id??'',arab:x.arabic||'',text:x.english?.text||'',narrator:x.english?.narrator||'',chapter:x.chapterId||n}));cache.set(key,a);return a}catch(e){last=e}}throw last||new Error('Sumber hadis tidak tersedia')}
function renderBooks(){const q=($('#hdSearch')?.value||'').trim().toLowerCase();$('#hdBooks').innerHTML=books.filter(b=>!q||b[1].toLowerCase().includes(q)||b[2].includes(q)).map(b=>`<article class="hd-book ${b[0]===active?'active':''}"><div class="hd-cover" style="background:linear-gradient(145deg,${b[5]},#082653)"><div class="arab">${esc(b[2])}</div><div class="latin">${esc(b[1])}</div><div class="author">${esc(b[3])}</div></div><div class="hd-meta"><strong>${esc(b[1])}</strong><small>${b[4]} bab · Arab + terjemahan Inggris</small><div class="hd-book-actions"><button class="hd-btn primary" data-open="${b[0]}">Baca Kitab</button><button class="hd-btn" data-download="${b[0]}">Unduh Kitab</button></div></div></article>`).join('')||'<div class="hd-empty">Kitab tidak ditemukan.</div>'}
function renderReader(items){const b=info(active);$('#hdReader').innerHTML=`<div class="hd-reader-head"><div class="hd-kicker">RUANG BACA HADITSMU</div><h2>${esc(b[1])}</h2><p>Bab ${chapter} dari ${b[4]} · ${items.length} hadis pada bab ini. Teks Arab + terjemahan Inggris.</p></div><div class="hd-chapters">${Array.from({length:b[4]},(_,i)=>`<button class="hd-btn ${i+1===chapter?'primary':''}" data-chapter="${i+1}">${i+1}</button>`).join('')}</div><div class="hd-list">${items.map(x=>`<article class="hd-item"><div class="hd-num">HADIS NO. ${esc(x.number)}</div>${x.arab?`<div class="hd-arab">${esc(x.arab)}</div>`:''}${x.narrator?`<div class="hd-note"><b>${esc(x.narrator)}</b></div>`:''}<p class="hd-en">${esc(x.text)}</p></article>`).join('')||'<div class="hd-empty">Bab ini kosong.</div>'}</div><div class="hd-pager"><button class="hd-btn" data-prev ${chapter<=1?'disabled':''}>Bab Sebelumnya</button><span>Bab ${chapter} / ${b[4]}</span><button class="hd-btn" data-next ${chapter>=b[4]?'disabled':''}>Bab Berikutnya</button></div>`}
async function openBook(id,n=1){if(loading)return;active=id;chapter=Math.max(1,Math.min(Number(n)||1,info(id)[4]));renderBooks();$('#hdReader').innerHTML='<div class="hd-empty">Memuat bab hadis…</div>';loading=true;try{const items=await fetchChapter(id,chapter);renderReader(items);$('#hdReader').scrollIntoView({block:'start',behavior:'smooth'})}catch(e){$('#hdReader').innerHTML='<div class="hd-empty"><strong>Kitab belum dapat dimuat.</strong><br>Sumber baca sedang tidak merespons. Tekan Baca Kitab lagi untuk mencoba ulang.</div>'}finally{loading=false}}
async function downloadBook(id){const btn=document.querySelector(`[data-download="${CSS.escape(id)}"]`);const b=info(id);if(btn){btn.disabled=true;btn.textContent='Menyiapkan…'}let all=[];try{for(let n=1;n<=b[4];n++){const part=await fetchChapter(id,n);all.push(...part);if(btn)btn.textContent=`Bab ${n}/${b[4]}`}const payload={kitab:b[1],judulArab:b[2],penulis:b[3],sumber:'AhmedBaset/hadith-json v1.2.0',bab:b[4],jumlah:all.length,hadis:all};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json;charset=utf-8'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=slug(id)+'-hadits.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2000);if(btn)btn.textContent='Selesai'}catch(e){if(btn)btn.textContent='Gagal — coba lagi';console.error(e)}finally{setTimeout(()=>{if(btn){btn.disabled=false;btn.textContent='Unduh Kitab'}},2200)}}
function slug(id){return id.replace(/[^a-z0-9]+/gi,'-')}
function bind(){$('#hdSearch').oninput=renderBooks;$('#hdBooks').onclick=e=>{const open=e.target.closest('[data-open]'),down=e.target.closest('[data-download]');if(open)openBook(open.dataset.open,1);if(down)downloadBook(down.dataset.download)};$('#hdReader').onclick=e=>{const c=e.target.closest('[data-chapter]'),p=e.target.closest('[data-prev]'),n=e.target.closest('[data-next]');if(c)openBook(active,Number(c.dataset.chapter));if(p&&!p.disabled)openBook(active,chapter-1);if(n&&!n.disabled)openBook(active,chapter+1)}}
async function mount(){const sec=$('#hadits');if(!sec||mounted)return;mounted=true;styles();sec.innerHTML=`<div class="hd-wrap"><section class="hd-hero"><div class="hd-kicker">HADITSMU • PERPUSTAKAAN HADIS</div><h1>HaditsMu</h1><p>Sembilan kitab hadis dengan cover kitab yang jelas. Pilih kitab, buka bab, baca teks Arab dan terjemahan, lalu unduh seluruh kitab sebagai berkas JSON.</p></section><div class="hd-tools"><input id="hdSearch" class="hd-search" placeholder="Cari nama kitab…"></div><div id="hdBooks" class="hd-bookgrid"></div><section id="hdReader" class="hd-reader"><div class="hd-empty">Pilih kitab untuk mulai membaca.</div></section></div>`;renderBooks();bind();openBook(active,1)}
window.PCMHadits={mount,openBook,downloadBook};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>{if(location.hash==='#hadits')mount()},{once:true});else if(location.hash==='#hadits')mount();})();