(()=>{'use strict';
const nativeFetch=window.fetch.bind(window);const arabicCache=new Map();let installed=false;
const map={abudawud:'abu-daud',tirmidhi:'tirmidzi',ibnmajah:'ibnu-majah',ahmad:'ahmad',bukhari:'bukhari',muslim:'muslim',nasai:'nasai',malik:'malik',darimi:'darimi'};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
async function retry(input,init){let last;for(let i=0;i<3;i++){try{const r=await nativeFetch(input,init);if(r.ok)return r;last=new Error('HTTP '+r.status)}catch(e){last=e}await sleep(350*(i+1))}throw last||new Error('Gagal memuat')}
async function gading(book,numbers){const out=[];const slug=map[book]||book;const sorted=[...new Set(numbers.map(Number).filter(Number.isFinite))].sort((a,b)=>a-b);if(!sorted.length)return out;let start=sorted[0];while(start<=sorted[sorted.length-1]){const end=Math.min(start+299,sorted[sorted.length-1]);try{const r=await nativeFetch(`https://api.hadith.gading.dev/books/${slug}?range=${start}-${end}`,{cache:'force-cache'});if(r.ok){const d=await r.json();const arr=d?.data?.hadiths||[];for(const x of arr){const n=x?.number??x?.contents?.number;if(n!=null&&sorted.includes(Number(n)))out.push({hadithnumber:n,text:x?.contents?.id||x?.id||''})}}}catch(_){}start=end+1}return out}
function install(){if(installed)return;installed=true;window.fetch=async function(input,init){const url=typeof input==='string'?input:input?.url||'';const isHadith=/cdn\.jsdelivr\.net\/gh\/fawazahmed0\/hadith-api@1\/editions\//i.test(url);if(!isHadith)return nativeFetch(input,init);const m=url.match(/\/editions\/(ara|ind)-([^/]+)\/sections\/(\d+)\.(?:json|min\.json)$/i);try{const r=await retry(input,init);if(m&&m[1].toLowerCase()==='ara'){try{arabicCache.set(`${m[2]}:${m[3]}`,await r.clone().json())}catch(_){}}return r}catch(e){if(!m)throw e;const key=`${m[2]}:${m[3]}`;if(m[1].toLowerCase()==='ind'){const a=arabicCache.get(key),nums=(a?.hadiths||[]).map(x=>x?.hadithnumber??x?.idInBook??x?.id).filter(x=>x!=null);const tr=await gading(m[2],nums);return new Response(JSON.stringify({hadiths:tr}),{status:200,headers:{'Content-Type':'application/json'}})}throw e}}}
install();
})();
