(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const SECTIONS=[['KhutbahMu','khutbah'],['KultumMu','kultum'],['BukuMu','buku'],['TafsirMu','tafsir']];
const BOOKCATS=[['Semua','all'],['Pedoman','pedoman'],['Referensi','referensi'],['Dakwah','dakwah'],['Bacaan','bacaan'],['Sejarah','sejarah'],['Ibadah','ibadah'],['Tarjih','tarjih'],['Booklet','booklet'],['Ramadhan','ramadhan'],['Kaderisasi','kaderisasi']];
const TAFSIR=[['Tafsir al-Tabari','tafsir tabari'],['Tafsir Ibn Kathir','tafsir ibn kathir'],['Tafsir al-Qurtubi','tafsir qurtubi'],['Tafsir al-Jalalayn','tafsir jalalayn'],['Tafsir al-Baghawi','tafsir baghawi'],['Tafsir al-Razi','tafsir razi'],['Tafsir al-Kashshaf','tafsir kashshaf'],['Tafsir al-Saadi','tafsir saadi'],['Tafsir al-Muyassar','tafsir muyassar'],['Tafsir As-Samarqandi','tafsir samarqandi'],['Tafsir al-Maturidi','tafsir maturidi'],['Tafsir al-Nasafi','tafsir nasafi'],['Tafsir Ruh al-Ma‘ani','tafsir ruh al maani'],['Tafsir Fi Zilal al-Quran','tafsir fi zilal al quran'],['Tafsir al-Misbah','tafsir al misbah']];
const MAX=1000000000000;
const state={section:'buku',cat:'all',q:'',page:1,items:[],total:0,req:0};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const short=v=>{v=String(v||'Dokumen').replace(/\s+/g,' ').trim();return v.length>58?v.slice(0,58).replace(/\s+\S*$/,'')+'…':v};
const pdf=x=>x.pdf_url||x.pdfUrl||x.pdf_source||x.cloudinary_pdf_url||'';
const docx=x=>x.docx_url||x.docxUrl||x.cloudinary_docx_url||'';
const cover=x=>x.cover_url||x.coverUrl||(x.identifier?`https://archive.org/services/img/${encodeURIComponent(x.identifier)}`:'');
function css(){if($('#pcm-stable-pustaka-css'))return;const s=document.createElement('style');s.id='pcm-stable-pustaka-css';s.textContent=`#pustaka .ps{max-width:1320px;margin:auto;padding:12px 0 60px}.ps-tabs,.ps-cats,.ps-pages{display:flex;gap:7px;overflow:auto;padding:6px 0}.ps-tabs button,.ps-cats button,.ps-pages button{border:1px solid #d5e3eb;background:#fff;color:#123d60;border-radius:11px;padding:10px 13px;font:inherit;font-weight:900;cursor:pointer;white-space:nowrap}.ps-tabs button.on,.ps-cats button.on,.ps-pages button.on{background:#075aa4;color:#fff;border-color:#075aa4}.ps-head{display:flex;gap:8px;align-items:center;margin:6px 0 10px}.ps-search{flex:1;padding:13px;border:1px solid #cbdde8;border-radius:12px;font:inherit}.ps-back{border:1px solid #cbdde8;background:#fff;color:#174563;border-radius:11px;padding:11px 13px;font-weight:900;cursor:pointer}.ps-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.ps-card{border:1px solid #d7e4eb;border-radius:17px;padding:9px;background:#fff;box-shadow:0 7px 20px #06265312}.ps-cover{aspect-ratio:2/3;border-radius:11px;overflow:hidden;background:linear-gradient(145deg,#07366c,#0b8f87);position:relative;cursor:pointer}.ps-cover img{width:100%;height:100%;object-fit:cover}.ps-cover span{position:absolute;inset:auto 0 0;padding:35px 9px 9px;color:#fff;font-weight:1000;background:linear-gradient(transparent,#001d35dd)}.ps-title{font-weight:1000;color:#082d58;line-height:1.3;margin-top:8px}.ps-author{font-size:.73rem;color:#637b8d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.ps-actions{display:flex;gap:5px;margin-top:8px}.ps-actions button{flex:1;border:0;border-radius:9px;padding:8px 4px;font:inherit;font-size:.72rem;font-weight:1000;cursor:pointer}.ps-preview{background:#075aa4;color:#fff}.ps-pdf{background:#a92d2d;color:#fff}.ps-docx{background:#1769aa;color:#fff}.ps-meta{font-size:.67rem;color:#0b8f87;font-weight:900;text-transform:uppercase;margin-top:5px}.ps-info{font-size:.78rem;color:#637b8d;margin:5px 0}.ps-pages{justify-content:center;flex-wrap:wrap}.ps-pages button:disabled{opacity:.4;cursor:not-allowed}.ps-empty{padding:40px;text-align:center;color:#637b8d}.ps-note{padding:10px 12px;background:#fff8df;border:1px solid #f0df9a;border-radius:10px;color:#68551d;font-size:.78rem;margin:8px 0}@media(max-width:1050px){.ps-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:800px){.ps-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.ps-grid{grid-template-columns:repeat(2,1fr);gap:8px}.ps-head{align-items:stretch;flex-direction:column}}`;document.head.appendChild(s)}
async function local(){let out=[];for(const f of ['data/pustaka-books.json','data/pustaka-catalog.json'])try{const j=await fetch(f+'?v=20260828-03',{cache:'no-store'}).then(r=>r.json());out.push(...(j.items||[]))}catch(e){}return out}
function isTafsir(x){const t=String([x.title,x.name,x.description,x.subjects].join(' ')).toLowerCase();const good=/(tafsir al[- ]tabari|tafsir ibn kathir|tafsir qurtubi|tafsir al[- ]jalalayn|tafsir al[- ]baghawi|tafsir al[- ]razi|tafsir al[- ]kashshaf|tafsir al[- ]sa.?di|tafsir al[- ]muyassar|tafsir as[- ]samarqandi|tafsir al[- ]maturidi|tafsir al[- ]nasafi|ruh al.?ma.?ani|fi zilal al.?quran|tafsir al.?misbah)/i.test(t);return good}
function matches(x){const t=String([x.title,x.name,x.description,x.subjects,x.category].join(' ')).toLowerCase();if(state.q&&!t.includes(state.q.toLowerCase()))return false;if(state.section==='tafsir')return isTafsir(x);if(state.section==='khutbah')return /(khutbah|khutba|jumat|jum'at)/i.test(t);if(state.section==='kultum')return /(kultum|kuliah tujuh menit|ceramah singkat|pengajian singkat)/i.test(t);if(state.section==='buku'){if(state.cat!=='all'&&String(x.category||'').toLowerCase()!==state.cat)return false;return !/(^|\s)(tafsir|hadits?|hadith|khutbah|kultum)(\s|$)/i.test(t)}return false}
function archiveQuery(){if(state.section==='tafsir')return TAFSIR[Math.min(state.page-1,TAFSIR.length-1)]?.[1]||'tafsir';if(state.section==='khutbah')return state.q||'khutbah jumat';if(state.section==='kultum')return state.q||'kultum ceramah';return state.q||'islam muhammadiyah'}
async function remote(){try{const q=encodeURIComponent(`mediatype:texts AND (${archiveQuery().split(/\s+/).filter(Boolean).slice(0,8).map(x=>'title:'+x.replace(/[^\p{L}0-9-]/gu,'')).join(' OR ')})`);const j=await fetch(`https://archive.org/advancedsearch.php?q=${q}&fl[]=identifier&fl[]=title&fl[]=creator&fl[]=year&fl[]=description&rows=24&page=${state.page}&output=json`,{cache:'no-store'}).then(r=>r.json());let docs=(j.response?.docs||[]).map(x=>({identifier:x.identifier,title:x.title,author:Array.isArray(x.creator)?x.creator.slice(0,2).join(', '):x.creator,year:x.year,description:x.description,source:'archive',category:state.section}));if(state.section==='tafsir')docs=docs.filter(isTafsir);state.total=Math.min(MAX,Number(j.response?.numFound||docs.length));return docs}catch(e){state.total=state.items.length;return[]}}
async function files(x){if(x.source!=='archive')return x;try{const j=await fetch('https://archive.org/metadata/'+encodeURIComponent(x.identifier),{cache:'no-store'}).then(r=>r.json());const fs=j.files||[],base='https://archive.org/download/'+encodeURIComponent(x.identifier)+'/';const p=fs.find(f=>/\.pdf$/i.test(String(f.name||''))),d=fs.find(f=>/\.docx$/i.test(String(f.name||'')));if(p)x.pdfUrl=base+encodeURIComponent(p.name);if(d)x.docxUrl=base+encodeURIComponent(d.name);x.coverUrl=x.coverUrl||`https://archive.org/services/img/${encodeURIComponent(x.identifier)}`}catch(e){}return x}
function card(x,i){const p=pdf(x),d=docx(x),c=cover(x);return `<article class="ps-card"><div class="ps-cover" data-preview="${i}"><img src="${esc(c)}" alt="" loading="lazy" onerror="this.style.display='none'"><span>${esc(short(x.title||x.name))}</span></div><div class="ps-meta">${esc(state.section)}</div><div class="ps-title">${esc(short(x.title||x.name))}</div><div class="ps-author">${esc(x.author||'')}</div><div class="ps-actions"><button class="ps-preview" data-preview="${i}">Pratinjau</button>${p?`<button class="ps-pdf" data-pdf="${i}">PDF</button>`:''}${d?`<button class="ps-docx" data-docx="${i}">DOCX</button>`:''}</div></article>`}
function open(x){window.PCMDocumentViewer?.open?.({title:x.title||x.name,pdfUrl:pdf(x),docxUrl:docx(x)})}
async function render(items){const arr=items.filter(matches);$('#psGrid').innerHTML=arr.map(card).join('')||'<div class="ps-empty">Tidak ada dokumen yang cocok pada halaman ini.</div>';$('#psInfo').textContent=`Halaman ${state.page} · ${state.total.toLocaleString('id-ID')} hasil terindeks`;$$('[data-preview]',$('#psGrid')).forEach(b=>b.onclick=async()=>{const x=await files(arr[+b.dataset.preview]);if(pdf(x)||docx(x))open(x);else alert('Berkas pratinjau belum terhubung pada sumber ini.')});$$('[data-pdf]',$('#psGrid')).forEach(b=>b.onclick=async()=>{const x=await files(arr[+b.dataset.pdf]);const u=pdf(x);if(u)location.href=u});$$('[data-docx]',$('#psGrid')).forEach(b=>b.onclick=async()=>{const x=await files(arr[+b.dataset.docx]);const u=docx(x);if(u)location.href=u});const pg=$('#psPages');const start=Math.max(1,state.page-2),end=Math.min(Math.max(1,Math.ceil(state.total/24)),state.page+2);pg.innerHTML=`<button data-page="${state.page-1}" ${state.page<=1?'disabled':''}>‹ Kembali</button>${Array.from({length:end-start+1},(_,i)=>start+i).map(n=>`<button class="${n===state.page?'on':''}" data-page="${n}">${n}</button>`).join('')}<button data-page="${state.page+1}" ${state.page>=Math.ceil(state.total/24)?'disabled':''}>Next ›</button>`;$$('button[data-page]',pg).forEach(b=>b.onclick=()=>{if(b.disabled)return;const n=Number(b.dataset.page);if(n<1||n>Math.ceil(state.total/24))return;state.page=n;loadPage()})}
async function loadPage(){const id=++state.req;$('#psGrid').innerHTML='<div class="ps-empty">Memuat katalog…</div>';const l=await local();let arr=l.filter(matches);const r=await remote();if(id!==state.req)return;const seen=new Set();state.items=[...arr,...r].filter(x=>{const k=String(x.title||x.name||x.identifier||'').toLowerCase();if(!k||seen.has(k))return false;seen.add(k);return true});await render(state.items)}
function shell(){const sec=$('#pustaka');if(!sec)return;css();sec.innerHTML=`<div class="ps"><div class="ps-head"><button class="ps-back" id="psBack">← Kembali</button><input id="psSearch" class="ps-search" placeholder="Cari judul, penulis, tema…"></div><div id="psTabs" class="ps-tabs"></div><div id="psCats" class="ps-cats"></div><div id="psInfo" class="ps-info"></div><div id="psGrid" class="ps-grid"></div><div id="psPages" class="ps-pages"></div><div class="ps-note">Pagination mengikuti jumlah dokumen yang benar-benar terindeks. Batas teknis dapat mencapai 1.000.000.000.000, tetapi halaman yang belum memiliki sumber dokumen tidak dibuat seolah-olah berisi.</div></div>`;$('#psBack').onclick=()=>{state.page=1;state.q='';state.section='buku';state.cat='all';drawTabs();loadPage()};$('#psSearch').oninput=e=>{state.q=e.target.value.trim();state.page=1;loadPage()};drawTabs();loadPage()}
function drawTabs(){const t=$('#psTabs');t.innerHTML=SECTIONS.map(([n,k])=>`<button class="${state.section===k?'on':''}" data-s="${k}">${n}</button>`).join('');$$('button',t).forEach(b=>b.onclick=()=>{state.section=b.dataset.s;state.cat='all';state.q='';state.page=1;$('#psSearch').value='';drawTabs();loadPage()});const c=$('#psCats');if(state.section==='buku'){c.style.display='flex';c.innerHTML=BOOKCATS.map(([n,k])=>`<button class="${state.cat===k?'on':''}" data-c="${k}">${n}</button>`).join('');$$('button',c).forEach(b=>b.onclick=()=>{state.cat=b.dataset.c;state.page=1;loadPage()})}else{c.style.display='none';c.innerHTML=''}}
function mount(route){state.section=SECTIONS.some(x=>x[1]===route)?route:'buku';state.cat='all';state.page=1;state.q='';state.items=[];state.total=0;shell()}
window.PCMPustakaStable={mount};})();