(()=>{'use strict';
const API='https://api.quranpedia.net/v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const norm=s=>String(s||'').toLowerCase().normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[^a-z0-9\u0600-\u06ff]+/g,'');
const get=async u=>{const r=await fetch(u,{cache:'no-store'});if(!r.ok)throw Error(r.status);return r.json()};
let targets=[],books=[];
function style(){if(document.getElementById('tfm-live-css'))return;const s=document.createElement('style');s.id='tfm-live-css';s.textContent=`#pustaka .tfml{max-width:1320px;margin:auto;padding:16px 12px 55px}.tfml-head{display:flex;align-items:center;gap:10px;margin-bottom:12px}.tfml-head h2{margin:0;color:#082d58}.tfml-badge{font-size:11px;font-weight:900;padding:5px 9px;border-radius:99px;background:#e7f4ef;color:#087052}.tfml-search{width:100%;box-sizing:border-box;padding:13px 15px;border:1px solid #c8d9e5;border-radius:12px;font:inherit}.tfml-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px;margin-top:14px}.tfml-card{background:#fff;border:1px solid #d5e2ea;border-radius:16px;padding:9px;box-shadow:0 5px 16px rgba(6,38,83,.08)}.tfml-cover{position:relative;aspect-ratio:2/3;border-radius:11px;overflow:hidden;background:#eef3f6}.tfml-cover iframe{width:100%;height:100%;border:0;background:#fff}.tfml-msg{position:absolute;inset:0;display:grid;place-items:center;text-align:center;padding:18px;color:#627888;font-weight:900}.tfml-title{font-weight:1000;color:#082d58;line-height:1.35;margin:9px 2px 3px}.tfml-author{font-size:.72rem;color:#687e90;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tfml-actions{display:grid;grid-template-columns:1fr 1fr;gap:6px;margin-top:9px}.tfml-actions button,.tfml-actions a{border:0;border-radius:8px;padding:9px 4px;text-align:center;text-decoration:none;font:inherit;font-size:.65rem;font-weight:1000;cursor:pointer}.tfml-read{background:#0a5ba5;color:#fff}.tfml-pdf{background:#c83d3d;color:#fff}.tfml-off{background:#e7ecef;color:#74818a;cursor:not-allowed!important}.tfml-modal{position:fixed;inset:0;z-index:999999;background:#202020;display:none;flex-direction:column}.tfml-modal.open{display:flex}.tfml-bar{display:flex;align-items:center;gap:8px;padding:8px;background:#16212b;color:#fff}.tfml-bar strong{flex:1;min-width:0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tfml-bar button,.tfml-bar a{border:0;border-radius:8px;padding:9px 12px;font:inherit;font-weight:900;text-decoration:none;cursor:pointer}.tfml-close{background:#eee;color:#222}.tfml-download{background:#ffc33d;color:#082d58}.tfml-frame{flex:1;width:100%;border:0;background:#fff}@media(max-width:1050px){.tfml-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:800px){.tfml-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.tfml-grid{grid-template-columns:repeat(2,1fr);gap:8px}.tfml-card{padding:6px}}`;document.head.appendChild(s)}
function author(a){return typeof a==='object'?String(a.full_name||a.ar_name||a.name||''):String(a||'')}
function score(b,t){const n=norm(b.name),q=norm(t.query),title=norm(t.title),a=norm(author(b.author)),w=norm(t.author);let z=0;if(n===q)z+=100;else if(n.includes(q)||q.includes(n))z+=60;if(n===title)z+=40;if(w&&a&&(a.includes(w)||w.includes(a)))z+=30;if(String(b.type||'').toLowerCase()==='tafsir')z+=20;return z}
async function pdf(atts){for(const a of atts||[]){const u=String(a.url||'');if(/\.pdf(?:\?|$)/i.test(u))return u}for(const a of atts||[]){const u=String(a.url||'');const m=u.match(/^https?:\/\/(?:www\.)?archive\.org\/(?:details|download)\/([^/?#]+)/i);if(!m)continue;try{const meta=await get('https://archive.org/metadata/'+encodeURIComponent(m[1]));const fs=(meta.files||[]).filter(f=>String(f.name||'').toLowerCase().endsWith('.pdf')).sort((x,y)=>Number(y.size||0)-Number(x.size||0));if(fs[0]?.name)return 'https://archive.org/download/'+encodeURIComponent(m[1])+'/'+encodeURIComponent(fs[0].name)}catch{}}return ''}
async function find(t){let hits=[];for(const q of [t.query,t.title]){try{const d=await get(API+'/search/'+encodeURIComponent(q)+'/books');for(const x of d.items||[]){const b=x.book_info||x;if(b.id&&!hits.some(h=>h.id===b.id))hits.push(b)}}catch{}}hits.sort((a,b)=>score(b,t)-score(a,t));const b=hits[0];if(!b||score(b,t)<45)return null;try{const d=await get(API+'/book/'+b.id);if(String(d.type||'').toLowerCase()!=='tafsir')return null;return{pdf:await pdf(d.book_attachments),name:d.name,author:author(d.author),id:d.id}}catch{return null}}
function modal(){let m=document.getElementById('tfml-modal');if(m)return m;document.body.insertAdjacentHTML('beforeend','<div id="tfml-modal" class="tfml-modal"><div class="tfml-bar"><button class="tfml-close">Tutup</button><strong id="tfml-name"></strong><a id="tfml-download" class="tfml-download" download>Download PDF</a></div><iframe id="tfml-frame" class="tfml-frame" title="Pratinjau kitab TafsirMu"></iframe></div>');m=document.getElementById('tfml-modal');m.querySelector('.tfml-close').onclick=()=>{m.classList.remove('open');document.getElementById('tfml-frame').src='about:blank';document.body.style.overflow=''};return m}
function draw(){const g=document.getElementById('tfml-grid');if(!g)return;const q=norm(document.getElementById('tfml-search')?.value||'');g.innerHTML=targets.map((t,i)=>({t,i})).filter(x=>!q||norm(x.t.title+' '+x.t.author).includes(q)).map(({t,i})=>{const b=books[i];if(!b)return '<article class="tfml-card"><div class="tfml-cover"><div class="tfml-msg">Menyiapkan PDF kitab asli…</div></div><div class="tfml-title">'+esc(t.title)+'</div><div class="tfml-author">'+esc(t.author)+'</div></article>';if(!b.pdf)return '<article class="tfml-card"><div class="tfml-cover"><div class="tfml-msg">PDF kitab asli belum tersedia</div></div><div class="tfml-title">'+esc(t.title)+'</div><div class="tfml-author">'+esc(t.author)+'</div><div class="tfml-actions"><button class="tfml-off" disabled>Pratinjau</button><button class="tfml-off" disabled>Download PDF</button></div></article>';return '<article class="tfml-card"><div class="tfml-cover"><iframe src="'+esc(b.pdf)+'#page=1&view=FitH" title="Cover asli '+esc(t.title)+'"></iframe></div><div class="tfml-title">'+esc(t.title)+'</div><div class="tfml-author">'+esc(t.author)+'</div><div class="tfml-actions"><button class="tfml-read" data-read="'+i+'">Pratinjau</button><a class="tfml-pdf" href="'+esc(b.pdf)+'" download target="_blank" rel="noopener">Download PDF</a></div></article>'}).join('');g.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>open(+b.dataset.read))}
function open(i){const b=books[i],t=targets[i];if(!b?.pdf)return;const m=modal();document.getElementById('tfml-name').textContent=t.title;document.getElementById('tfml-frame').src=b.pdf+'#page=1&view=FitH';const a=document.getElementById('tfml-download');a.href=b.pdf;a.download=t.title+'.pdf';m.classList.add('open');document.body.style.overflow='hidden'}
async function render(){const r=document.getElementById('pustaka');if(!r)return;style();r.innerHTML='<div class="tfml"><div class="tfml-head"><h2>TafsirMu</h2><span class="tfml-badge">PDF ASLI • PRATINJAU PENUH</span></div><input id="tfml-search" class="tfml-search" placeholder="Cari kitab tafsir, pengarang…" autocomplete="off"><div id="tfml-grid" class="tfml-grid"></div></div>';document.getElementById('tfml-search').oninput=draw;try{targets=(await get('data/tafsir-40-targets.json?v=20260829-06')).items||[]}catch{targets=[]}books=targets.map(()=>null);draw();books=await Promise.all(targets.map(t=>find(t).catch(()=>null)));draw()}
function go(e){const a=e.target.closest?.('a[href="#tafsir"],a[data-pcm-route="tafsir"]');if(!a)return;e.preventDefault();history.replaceState(null,'','#tafsir');const p=document.getElementById('pustaka');if(p){p.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x===p))}render()}
document.addEventListener('click',go,true);window.addEventListener('hashchange',()=>location.hash.replace('#','').toLowerCase()==='tafsir'&&render());document.addEventListener('DOMContentLoaded',()=>location.hash.replace('#','').toLowerCase()==='tafsir'&&render());window.PCMTafsirLive={mount:render};})();