(()=>{'use strict';
const API='https://api.quranpedia.net/v1';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
let state={items:[],q:'',page:1};
const esc=v=>String(v??'').replace(/[&<>\"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[m]));
const short=v=>{const s=String(v||'').replace(/\s+/g,' ').trim();return s.length>54?s.slice(0,54).replace(/\s+\S*$/,'')+'…':s};
async function get(url){const r=await fetch(url,{cache:'force-cache'});if(!r.ok)throw Error(String(r.status));return r.json()}
function score(book,t){const n=String(book?.name||'').toLowerCase(),a=String(book?.author?.full_name||book?.author||'').toLowerCase(),q=String(t.query||'').toLowerCase(),au=String(t.author||'').toLowerCase();return (n===q?100:0)+(n.includes(q)||q.includes(n)?35:0)+(au&&a&&(a.includes(au)||au.includes(a))?25:0)+(String(book?.type||'').toLowerCase()==='tafsir'?20:0)}
async function resolve(t){const d=await get(`${API}/search/${encodeURIComponent(t.query)}/books`);const arr=d?.books?.items||d?.items||[];let cand=[...arr].sort((a,b)=>score(b,t)-score(a,t));const b=cand[0];if(!b?.id)throw Error('not-found');const detail=await get(`${API}/book/${b.id}`);const at=(detail.book_attachments||[]).map(a=>({url:String(a.url||''),name:a.name||'',part:a.part||1})).filter(a=>/^https?:/i.test(a.url));const pdfs=at.filter(a=>/\.pdf(?:\?|$)/i.test(a.url));const docx=at.filter(a=>/\.(?:docx?|DOCX?)\b/i.test(a.url));return {target:t,book:detail,pdf:pdfs.sort((a,b)=>a.part-b.part)[0]?.url||'',pdfs:pdfs.sort((a,b)=>a.part-b.part).map(x=>x.url),docx:docx[0]?.url||'',contents:detail.contents_url||'',id:detail.id,language:detail.language?.code||''}}
async function load(){const targets=await get('data/tafsir-40-targets.json?v=20260828-05');const ts=targets.items||[];const out=[];const chunk=async arr=>{const r=await Promise.all(arr.map(resolve));r.forEach(x=>out.push(x))};for(let i=0;i<ts.length;i+=6){await chunk(ts.slice(i,i+6))}state.items=out;}
function sort(){state.items.sort((a,b)=>{const ai=/^(id|indonesian|indonesia)$/i.test(a.language),bi=/^(id|indonesian|indonesia)$/i.test(b.language);return Number(bi)-Number(ai)||String(a.target.title).localeCompare(String(b.target.title),'id')})}
async function cover(canvas,url){if(!url)return;try{const pdfjs=await import('https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.min.mjs');pdfjs.GlobalWorkerOptions.workerSrc='https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.4.168/pdf.worker.min.mjs';const doc=await pdfjs.getDocument({url,withCredentials:false}).promise;const p=await doc.getPage(1);const box=canvas.getBoundingClientRect();const v0=p.getViewport({scale:1});const scale=Math.max(.5,Math.min(1.3,(box.width||200)/v0.width));const v=p.getViewport({scale});const d=Math.min(devicePixelRatio||1,2);canvas.width=Math.ceil(v.width*d);canvas.height=Math.ceil(v.height*d);canvas.style.width='100%';canvas.style.height='100%';await p.render({canvasContext:canvas.getContext('2d'),viewport:v,transform:[d,0,0,d,0,0]}).promise;}catch(e){canvas.parentElement.classList.add('no-cover')}}
function openBook(x){if(!x.pdf)return;window.PCMDocumentViewer?.open?.({title:x.target.title,pdfUrl:x.pdf,docxUrl:x.docx,coverUrl:''})}
async function makeDocx(x){if(x.docx){const a=document.createElement('a');a.href=x.docx;a.download=short(x.target.title)+'.docx';a.target='_blank';a.rel='noopener';a.click();return}if(!x.contents)return;try{const pkg=await import('https://cdn.jsdelivr.net/npm/docx@9.5.1/+esm');const d=await get(x.contents);const rows=Array.isArray(d)?d:(d.items||d.content||[]);const doc=new pkg.Document({sections:[{properties:{},children:rows.map(r=>new pkg.Paragraph({text:String(r.text||r.content||''),bidirectional:/[\u0600-\u06ff]/.test(String(r.text||r.content||''))}))} ]});const blob=await pkg.Packer.toBlob(doc);const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=short(x.target.title)+'.docx';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),10000)}catch(e){}}
function draw(){const g=$('#tmfGrid');if(!g)return;let rows=state.items.filter(x=>{const q=state.q.trim().toLowerCase();return !q||[x.target.title,x.target.author,x.book?.name,x.book?.publish_year].join(' ').toLowerCase().includes(q)});const pages=Math.max(1,Math.ceil(rows.length/20));state.page=Math.min(state.page,pages);rows=rows.slice((state.page-1)*20,state.page*20);g.innerHTML=rows.map((x,i)=>`<article class="tmf-card"><button class="tmf-cover" data-i="${i}" aria-label="Buka ${esc(short(x.target.title))}"><canvas></canvas><span>${esc(short(x.target.title))}</span></button><h3>${esc(short(x.target.title))}</h3><p>${esc(x.target.author||x.book?.author?.full_name||'')}</p>${x.book?.publish_year?`<small>${esc(x.book.publish_year)}</small>`:''}<div class="tmf-actions"><button data-open="${i}">Pratinjau</button><button data-pdf="${i}">PDF</button><button data-docx="${i}">DOCX</button></div></article>`).join('');
$$('[data-i]',g).forEach((b,i)=>cover($('canvas',b),rows[i].pdf));$$('[data-open]',g).forEach(b=>b.onclick=()=>openBook(rows[+b.dataset.open]));$$('[data-pdf]',g).forEach(b=>b.onclick=()=>{const x=rows[+b.dataset.pdf];if(x.pdf){const a=document.createElement('a');a.href=x.pdf;a.download=short(x.target.title)+'.pdf';a.target='_blank';a.rel='noopener';a.click()}});$$('[data-docx]',g).forEach(b=>b.onclick=()=>makeDocx(rows[+b.dataset.docx]));
const p=$('#tmfPages');p.innerHTML=Array.from({length:Math.min(4,pages)},(_,i)=>`<button class="${i+1===state.page?'on':''}" data-p="${i+1}">${i+1}</button>`).join('')+(state.page<pages?'<button data-next>Next</button>':'');$$('[data-p]',p).forEach(b=>b.onclick=()=>{state.page=+b.dataset.p;draw()});$('[data-next]',p)?.addEventListener('click',()=>{state.page++;draw()})}
function css(){if($('#tmfCss'))return;const s=document.createElement('style');s.id='tmfCss';s.textContent=`#pustaka .tmf{max-width:1320px;margin:auto;padding:10px 0 60px}.tmf-search{width:100%;box-sizing:border-box;padding:13px 15px;border:1px solid #cbdde8;border-radius:13px;font:inherit;margin-bottom:15px}.tmf-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.tmf-card{background:#fff;border:1px solid #d7e4eb;border-radius:17px;padding:9px;min-width:0;box-shadow:0 7px 20px #06265312}.tmf-cover{width:100%;aspect-ratio:2/3;border:0;border-radius:11px;overflow:hidden;background:#f4efe5;position:relative;padding:0;cursor:pointer;display:block}.tmf-cover canvas{width:100%;height:100%;display:block;object-fit:cover}.tmf-cover.no-cover{background:linear-gradient(145deg,#0c3c67,#0b847f)}.tmf-cover span{position:absolute;left:0;right:0;bottom:0;padding:35px 9px 9px;color:#fff;font-weight:1000;text-align:left;background:linear-gradient(transparent,#001d35df)}.tmf-card h3{font-size:.9rem;line-height:1.35;color:#082d58;margin:8px 2px 2px}.tmf-card p{margin:0 2px;font-size:.72rem;color:#637b8d;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.tmf-card small{display:block;margin:3px 2px;color:#7890a0;font-size:.68rem}.tmf-actions{display:flex;gap:5px;margin-top:9px}.tmf-actions button{flex:1;border:0;border-radius:9px;padding:8px 3px;font:inherit;font-size:.64rem;font-weight:1000;cursor:pointer;background:#ffbf32;color:#08335e}.tmf-pages{display:flex;justify-content:center;gap:6px;margin-top:20px;flex-wrap:wrap}.tmf-pages button{border:1px solid #cbdde8;background:#fff;color:#174563;border-radius:9px;padding:8px 12px;font:inherit;font-weight:900;cursor:pointer}.tmf-pages button.on{background:#075aa4;color:#fff}@media(max-width:1050px){.tmf-grid{grid-template-columns:repeat(4,1fr)}}@media(max-width:800px){.tmf-grid{grid-template-columns:repeat(3,1fr)}}@media(max-width:560px){.tmf-grid{grid-template-columns:repeat(2,1fr);gap:8px}.tmf-card{padding:7px}.tmf-actions button{font-size:.57rem;padding:7px 2px}}`;document.head.appendChild(s)}
async function mount(){css();const sec=$('#pustaka');if(!sec)return;sec.innerHTML='<div class="tmf"><input class="tmf-search" id="tmfSearch" placeholder="Cari kitab tafsir…"><div class="tmf-grid" id="tmfGrid"></div><div class="tmf-pages" id="tmfPages"></div></div>';$('#tmfSearch').oninput=e=>{state.q=e.target.value;state.page=1;draw()};await load();sort();draw()}
window.PCMTafsirFinal={mount};})();